import { useEffect, useState, type ReactNode } from 'react';
import { Radio, MessageSquare, FileText, Activity, Building2, Send, RefreshCw } from 'lucide-react';
import type { State } from './state';
import { eventTime } from './state';
import { alertDraft, routeDecision, zones, type ZoneId } from './operations';
import { LiveFeeds } from './LiveFeeds';
type Asset={id:string;name:string;kind:string;coordinates:number[]};
type Receipt={zone:ZoneId;status:string;count:number;time:string;revision:number};
const tabs=['Situation','Assets','Notify','Media','Sources','Plan'];
export function ControlTower({state,zone,setZone,plan,motionNotified}:{motionNotified:number;state:State;zone:ZoneId;setZone:(z:ZoneId)=>void;plan:ReactNode}){
 const [tab,setTab]=useState('Situation'); const [assets,setAssets]=useState<Asset[]>([]);const [snapshot,setSnapshot]=useState('');const [coverageError,setCoverageError]=useState('');const [filter,setFilter]=useState('hospital');
 const [receipts,setReceipts]=useState<Receipt[]>([]);const [reviewed,setReviewed]=useState(false);const [mediaPrompt,setMediaPrompt]=useState('Prepare a calm, 30-second local radio bulletin. Explain the affected area, what is known, what is unverified, and where residents should get official updates.');const [bulletin,setBulletin]=useState('');const [copied,setCopied]=useState('');
 useEffect(()=>{fetch('/data/infrastructure.json').then(r=>{if(!r.ok)throw Error('Facility inventory unavailable');return r.json()}).then(d=>{setAssets(d.assets);setSnapshot(d.fetchedAt)}).catch(e=>setCoverageError(e.message))},[]);
 useEffect(()=>{setReviewed(false);setBulletin('')},[zone,state.condition?.type,state.revision]);
 const decision=routeDecision(zone,state.condition?.type);const z=zones.find(z=>z.id===zone)!;const notified=receipts.filter(r=>r.status==='Simulated delivered').reduce((n,r)=>n+r.count,0);
 const simulate=()=>{setReceipts(old=>[...old,{zone,status:'Simulated delivered',count:Math.floor(z.homes*.92),time:new Date().toLocaleTimeString(),revision:state.revision},{zone,status:'Simulated failed',count:Math.ceil(z.homes*.08),time:new Date().toLocaleTimeString(),revision:state.revision}]);setReviewed(false)};
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);setCopied('Copied')}catch{setCopied('Select the text to copy')} };
 return <aside className="tower"><div className="tower-heading"><div><span className="eyebrow">RESPONSE CONTROL</span><h2>Incident control tower</h2></div><Radio size={22}/></div>
 <div className="notification-summary"><MessageSquare size={18}/><strong>{(motionNotified||notified).toLocaleString()}</strong><span>{motionNotified?"playback notified":"demo deliveries"}</span><b>0 real sent</b></div>
 <nav className="tower-tabs" aria-label="Control tower panels">{tabs.map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 <div className="tower-body">
 {tab==='Situation'&&<><div className="tower-label"><Activity size={15}/> Incident report <span>Exercise</span></div><h3>{state.condition?state.condition.type.replaceAll('_',' '):'Palisades response area'}</h3><p>{state.condition?`Latest exercise change: ${state.condition.target}.`:'Fire, communities, medical facilities and infrastructure in one operating picture.'}</p>
 <label className="field-label" htmlFor="zone">Residence / evacuation zone</label><select id="zone" value={zone} onChange={e=>setZone(e.target.value as ZoneId)}>{zones.map(z=><option key={z.id} value={z.id}>Zone {z.id} · {z.name}</option>)}</select>
 <div className={`route-card ${decision.available?'':'held'}`}><span>{decision.status}</span><h3>{decision.detail}</h3>{decision.available&&<p>{z.corridor}</p>}<small>Diagram arrows are conceptual exercise directions, not turn-by-turn routes.</small></div>
 <div className="tower-label">Corridor status <span>Scenario only</span></div><div className="status-row"><span>Pacific Coast Highway</span><b className={state.condition?.type==='road_blocked'?'bad':'warn'}>{state.condition?.type==='road_blocked'?'Closed · demo':'Unknown'}</b></div><div className="status-row"><span>Sunset / Chautauqua</span><b className="warn">Unverified</b></div><div className="status-row"><span>San Vicente</span><b className="warn">Unverified</b></div>
 <div className="tower-label">Responder movement <span>Simulated</span></div><div className="dispatch-row"><b>Engine 23 ↑</b><span>North → perimeter staging</span></div><div className="dispatch-row"><b>Engine 69 ←</b><span>West → eastern flank</span></div><small>Station locations are mapped inventory. Vehicle arrows are exercise assignments; no dispatch / GPS feed is connected.</small>
 <div className="tower-label">Latest incident activity</div>{state.events.slice(-5).reverse().map(e=><div className="report-entry" key={`${e.run_id}-${e.seq}`}><time>{new Date(eventTime(e.ts)).toLocaleTimeString()}</time><p>{e.message||e.event_type.replaceAll('_',' ')}</p></div>)}{!state.events.length&&<p>No agent events yet. Start response to populate the report.</p>}</>}
 {tab==='Assets'&&<><div className="tower-label"><Building2 size={16}/> Mapped infrastructure</div><p>Mapped features within the response area. OpenStreetMap coverage may be incomplete; operating status is not supplied.</p><div className="asset-filters">{['hospital','fire_station','power'].map(t=><button key={t} onClick={()=>setFilter(t)} className={filter===t?'selected':''}>{t==='hospital'?'Hospitals':t==='power'?'Power lines':'Fire stations'} <b>{assets.filter(a=>a.kind===t).length}</b></button>)}</div>{coverageError&&<p role="alert">{coverageError}</p>}{assets.filter(a=>a.kind===filter).map(a=><div className="asset-row" key={a.id}><strong>{a.name}</strong><span>{filter==='hospital'?'Capacity / emergency intake unknown':filter==='power'?'Energization / damage unknown':'Dispatch status unknown'}</span></div>)}<small>Inventory retrieved {snapshot?new Date(snapshot).toLocaleString():'—'} · © OpenStreetMap contributors</small></>}
 {tab==='Notify'&&<><div className="tower-label"><MessageSquare size={16}/> Public notification agent <span>Demo</span></div><h3>Address zone → route review → alert</h3><p>Zone {zone} · {z.name}. {z.homes} fictional households in this exercise cohort.</p><textarea aria-label="SMS exercise draft" readOnly value={alertDraft(zone,state.condition?.type)} rows={9}/><label className="review-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Review this exercise draft</label><button className="primary wide" disabled={!reviewed||!decision.available||receipts.some(r=>r.zone===zone&&r.revision===state.revision)} onClick={simulate}><Send size={16}/>Simulate notification delivery</button><small>No SMS provider or real phone numbers are connected. Delivery counts below are generated exercise outcomes.</small><div className="tower-label">Notification ledger</div>{motionNotified>0&&<div className="receipt"><strong>Map playback · {motionNotified} fictional households notified</strong><small>Open the map notification panel for Zone A/B/C progress. Separate from manually simulated deliveries below.</small></div>}{receipts.length?receipts.map((r,i)=><div className="receipt" key={i}><strong>Zone {r.zone} · {r.count} demo households</strong><span className={r.status.includes('failed')?'bad':''}>{r.status}</span><small>{r.time} · revision {r.revision}</small></div>):<p>No manual deliveries. No real messages sent.</p>}</>}
 {tab==='Media'&&<><div className="tower-label"><FileText size={16}/> Media briefing assistant</div><label className="field-label" htmlFor="media-prompt">Briefing prompt</label><textarea id="media-prompt" value={mediaPrompt} onChange={e=>setMediaPrompt(e.target.value)} rows={5}/><button className="primary wide" onClick={()=>{setCopied('');setBulletin(`EXERCISE / DRAFT — NOT FOR BROADCAST\n\nEditorial brief: ${mediaPrompt}\n\nThis is a ResponseGrid exercise update for Pacific Palisades. The scenario involves wildfire impacts near ${z.name}. ${state.condition?`The latest simulated change is ${state.condition.type.replaceAll('_',' ')}.`:'Specialists are assessing fire, transportation, medical care and utilities.'} Road availability, hospital capacity and power status have not been verified. No real evacuation order or route is issued by this demonstration. For an actual incident, use official local emergency alerts and verified agency updates.\n\nPRODUCER CHECK: Confirm issuing authority, affected boundaries, approved instructions, timestamp and next update before broadcast.`)}}><RefreshCw size={16}/>Build briefing draft</button>{bulletin&&<><textarea aria-label="Media bulletin draft" value={bulletin} onChange={e=>setBulletin(e.target.value)} rows={15}/><button onClick={()=>copy(bulletin)}>{copied||'Copy draft'}</button></>}<small>Local template assistant. No newsroom distribution or language-model generation is connected.</small></>}
 {tab==='Sources'&&<><LiveFeeds/><h3>Data provenance & freshness</h3><p>Imagery does not establish road safety, utility energization, hospital capacity or vehicle position.</p>{[
 ['USGS topography / imagery','Basemap available','Acquisition time varies by tile; not live satellite surveillance.','https://www.usgs.gov/programs/national-geospatial-program/national-map'],
 ['OpenStreetMap infrastructure','Downloaded inventory',snapshot?`Retrieved ${new Date(snapshot).toLocaleString()}. Completeness not guaranteed.`:'Inventory loading.','https://www.openstreetmap.org/copyright'],
 ['Traffic / closures','Caltrans feed above','Local closures and vehicle speeds still require integration.','https://quickmap.dot.ca.gov/'],
 ['Utility outages','Not connected','Requires LADWP / utility operational status.','https://www.ladwp.com/outages'],
 ['Fire dispatch / vehicle GPS','Not connected','Requires authorized CAD / AVL integration.','https://www.lafd.org/'],
 ['Emergency alerts / SMS','Not connected','Provider credentials, approved recipients and delivery callbacks required.','https://www.fema.gov/emergency-managers/practitioners/integrated-public-alert-warning-system'],
 ].map(([name,status,detail,url])=><div className="source-card" key={name}><strong>{name}</strong><b>{status}</b><p>{detail}</p><a href={url} target="_blank" rel="noreferrer">Open source ↗</a></div>)}</>}
 {tab==='Plan'&&plan}
 </div></aside>
}
