import { memo, useEffect, useRef, useState } from 'react';
import { Map as LibreMap, setWorkerUrl, NavigationControl, ScaleControl, AttributionControl, Marker, Popup, type GeoJSONSource, type StyleSpecification } from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import mapWorkerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
setWorkerUrl(mapWorkerUrl);
import { Mountain, LocateFixed, Layers, X, RadioTower, Maximize, Minimize, Hospital, Zap } from 'lucide-react';
import { FireBadge, fireBadgeSVG } from './FireBadge';
import { MapSimulation } from './MapSimulation';
import {  zones, type ZoneId } from './operations';
import type { State } from './state';
import type { FeatureCollection, Feature } from 'geojson';

const HOME = { center: [-118.537, 34.066] as [number,number], zoom: 12.2, pitch: 0, bearing: 0 };
const INCIDENT_BOUNDS: [[number, number], [number, number]] = [[-118.635, 34.0], [-118.425, 34.14]];
const USGS = 'https://basemap.nationalmap.gov/arcgis/rest/services';
const EMPTY: FeatureCollection = { type:'FeatureCollection', features:[] };
const style: StyleSpecification = {
  version:8,
  glyphs:"https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf",
  sources: {
    topographic: {type:'raster',tiles:[`${USGS}/USGSTopo/MapServer/tile/{z}/{y}/{x}`],tileSize:256,maxzoom:16,attribution:'<a href="https://www.usgs.gov/programs/national-geospatial-program/national-map">USGS The National Map</a>'},
    satellite: {type:'raster',tiles:[`${USGS}/USGSImageryTopo/MapServer/tile/{z}/{y}/{x}`],tileSize:256,maxzoom:16,attribution:'USGS · The National Map imagery'},
    elevation: {type:'raster-dem',tiles:['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],encoding:'terrarium',tileSize:256,maxzoom:15,attribution:'<a href="https://github.com/tilezen/joerd/blob/master/docs/attribution.md">Terrain: Mapzen / USGS / NASA</a>'},
    incident:{type:'geojson',data:EMPTY}, infrastructure:{type:'geojson',data:EMPTY,attribution:'© OpenStreetMap contributors'}, operations:{type:'geojson',data:EMPTY}, blackouts:{type:'geojson',data:EMPTY}, grid:{type:'geojson',data:EMPTY},
  },
  layers:[
    {id:'topographic',type:'raster',source:'topographic',paint:{'raster-fade-duration':200}},
    {id:'satellite',type:'raster',source:'satellite',layout:{visibility:'none'},paint:{'raster-fade-duration':200}},
    {id:'hillshade',type:'hillshade',source:'elevation',paint:{'hillshade-exaggeration':.22,'hillshade-shadow-color':'#43473b','hillshade-highlight-color':'#ffffff'}},
    {id:'road-inventory',type:'line',source:'infrastructure',filter:['==',['get','kind'],'road'],paint:{'line-color':'#607586','line-width':2,'line-opacity':.55}},
    {id:'power-halo',type:'line',source:'infrastructure',filter:['==',['get','kind'],'power'],paint:{'line-color':'#ffffff','line-width':7,'line-opacity':.8}},
    {id:'power-inventory',type:'line',source:'infrastructure',filter:['==',['get','kind'],'power'],paint:{'line-color':'#a653cf','line-width':['interpolate',['linear'],['zoom'],10,2.5,14,4.5],'line-opacity':1}},
    {id:'grid-fill',type:'fill',source:'grid',paint:{'fill-color':'#42ae83','fill-opacity':.13}},
    {id:'grid-edge',type:'line',source:'grid',paint:{'line-color':'#279570','line-width':1.5}},
    {id:'grid-label',type:'symbol',source:'grid',layout:{'text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':11},paint:{'text-color':'#196746','text-halo-color':'#ffffff','text-halo-width':2}},
    {id:'blackout-fill',type:'fill',source:'blackouts',paint:{'fill-color':'#26384d','fill-opacity':.29}},
    {id:'blackout-edge',type:'line',source:'blackouts',paint:{'line-color':'#58718c','line-width':2,'line-dasharray':[2,2]}},
    {id:'blackout-label',type:'symbol',source:'blackouts',layout:{'text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':12},paint:{'text-color':'#fff','text-halo-color':'#27394e','text-halo-width':2}},
    {id:'ops-routes',type:'line',source:'operations',filter:['in',['get','kind'],['literal',['egress','responder']]],paint:{'line-color':['case',['==',['get','kind'],'responder'],'#ef784b',['==',['get','status'],'held'],'#d73b26','#078e9c'],'line-width':2.5,'line-opacity':.38}},
    {id:'ops-labels',type:'symbol',source:'operations',filter:['in',['get','kind'],['literal',['egress','responder']]],layout:{'symbol-placement':'line','text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':12,'text-offset':[0,-1]},paint:{'text-color':'#193d56','text-halo-color':'#ffffff','text-halo-width':2}},
    {id:'evacuation-fill',type:'fill',source:'incident',filter:['==',['get','kind'],'evacuation'],paint:{'fill-color':'#e4ac32','fill-opacity':.13}},
    {id:'evacuation-line',type:'line',source:'incident',filter:['==',['get','kind'],'evacuation'],paint:{'line-color':'#956315','line-width':2,'line-dasharray':[3,2]}},
    {id:'fire-fill',type:'fill',source:'incident',filter:['==',['get','kind'],'fire'],paint:{'fill-color':'#ec623f','fill-opacity':.13}},
    {id:'fire-edge',type:'line',source:'incident',filter:['==',['get','kind'],'fire'],paint:{'line-color':'#c33f25','line-width':3}},
    {id:'closure',type:'circle',source:'incident',filter:['==',['get','kind'],'closure'],paint:{'circle-radius':11,'circle-color':'#bd3928','circle-stroke-color':'#fff','circle-stroke-width':3}},
    {id:'impact',type:'circle',source:'incident',filter:['==',['get','kind'],'impact'],paint:{'circle-radius':26,'circle-color':'#ee9c30','circle-opacity':.3,'circle-stroke-color':'#b05c16','circle-stroke-width':2}},
  ]
};
function incidentData(kind?:string,elapsed=0):FeatureCollection{
 const expanded=kind==='wind_shift'||kind==='new_hazard_zone';
 const fire=[[-118.565,34.097],[-118.551,34.101],[-118.541,34.094],[-118.525,34.091],[-118.518,34.078],[-118.529,34.066],[-118.547,34.065],[-118.56,34.076],[-118.565,34.097]];
 if(expanded){fire[4]=[-118.504,34.079];fire[5]=[-118.512,34.060]}
 const growth=Math.min(elapsed/180,1)*.12;for(const p of fire){p[0]=-118.547+(p[0]+118.547)*(1+growth)+growth*.012;p[1]=34.083+(p[1]-34.083)*(1+growth)}
 const evacuation=[[-118.576,34.102],[-118.539,34.11],[-118.503,34.091],[-118.499,34.055],[-118.533,34.045],[-118.57,34.065],[-118.576,34.102]];
 const features:Feature[]=[{type:'Feature',properties:{kind:'fire'},geometry:{type:'Polygon',coordinates:[fire]}},{type:'Feature',properties:{kind:'evacuation'},geometry:{type:'Polygon',coordinates:[evacuation]}}];
 if(kind==='road_blocked')features.push({type:'Feature',properties:{kind:'closure'},geometry:{type:'Point',coordinates:[-118.5356,34.0348]}});
 if(kind&&kind!=='road_blocked')features.push({type:'Feature',properties:{kind:'impact'},geometry:{type:'Point',coordinates:kind==='hospital_power_loss'?[-118.4795,34.0307]:kind==='shelter_full'?[-118.503,34.041]:[-118.53,34.078]}});
 return {type:'FeatureCollection',features};
}
export const IncidentMap=memo(function IncidentMap({state,zone,setZone,onNotified}:{state:State;zone:ZoneId;setZone:(zone:ZoneId)=>void;onNotified:(n:number)=>void}){
 const [powerFocus,setPowerFocus]=useState(false);
 const [facilityView,setFacilityView]=useState<'hospital'|'fire_station'|null>(null);const [facilities,setFacilities]=useState<{id:string;name:string;kind:string;coordinates:[number,number]}[]>([]);
 const [hazardTime,setHazardTime]=useState(0);
 const [inventoryError,setInventoryError]=useState('');const [inventoryCount,setInventoryCount]=useState('Loading infrastructure…');const [visibility,setVisibility]=useState({hospital:true,fire_station:true,power:true,road:false});const inventoryMarkers=useRef<{marker:Marker;kind:string;id:string}[]>([]);const zoneMarkers=useRef<Marker[]>([]);const closureMarkers=useRef<Marker[]>([]);
 const panel=useRef<HTMLElement>(null);const [full,setFull]=useState(false);
 const container=useRef<HTMLDivElement>(null);const map=useRef<LibreMap|null>(null);const [loaded,setLoaded]=useState(false);const [error,setError]=useState('');const [basemap,setBasemap]=useState<'topographic'|'satellite'>('topographic');const [terrain,setTerrain]=useState(false);const [layersOpen,setLayersOpen]=useState(false);const [overlays,setOverlays]=useState(true);const [attempt,setAttempt]=useState(0);const [elevation,setElevation]=useState<number|null>(null);const markers=useRef<Marker[]>([]);
 useEffect(()=>{
  if(!container.current)return;
  setLoaded(false);setError('');let disposed=false;let m:LibreMap;
  try{m=new LibreMap({container:container.current,style,...HOME,bounds:INCIDENT_BOUNDS,fitBoundsOptions:{padding:35},minZoom:7,maxZoom:17,attributionControl:false,renderWorldCopies:false});map.current=m;}catch{setError('The interactive map could not start. Enable browser graphics acceleration, then retry.');return}
  m.addControl(new NavigationControl({visualizePitch:true}),'top-right');m.addControl(new ScaleControl({maxWidth:130,unit:'imperial'}),'bottom-left');m.addControl(new AttributionControl({compact:true}),'bottom-right');
  m.on('style.load',()=>{if(disposed)return;setLoaded(true);setError('');
   const places:[string,[number,number],string][]=[['Fire perimeter',[-118.547,34.084],'fire']];
   places.forEach(([name,lnglat,type])=>{const el=document.createElement('button');el.className=`geo-marker ${type}`;el.type='button';el.textContent=type==='hospital'?'+':type==='shelter'?'S':'Fire perimeter';el.setAttribute('aria-label',`${name} — simulation overlay`);const content=document.createElement('div');const heading=document.createElement('strong');heading.textContent=name;const detail=document.createElement('p');detail.textContent='Simulation overlay. Approximate incident location; not a live emergency feed.';content.append(heading,detail);markers.current.push(new Marker({element:el}).setLngLat(lnglat).setPopup(new Popup({offset:20}).setDOMContent(content)).addTo(m))});
  });
  m.once('style.load',()=>{
   fetch('/data/infrastructure.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{if(disposed)return;(m.getSource('infrastructure') as GeoJSONSource).setData(d.geojson);setFacilities(d.assets.filter((a:any)=>a.kind!=='power'));setInventoryCount(`${d.assets.filter((a:any)=>a.kind==='hospital').length} hospitals · ${d.assets.filter((a:any)=>a.kind==='fire_station').length} fire-service features · mapped coverage`);
    d.assets.filter((a:any)=>a.kind!=='power').forEach((a:any)=>{const el=document.createElement('button');el.className=`geo-marker ${a.kind==='hospital'?'facility':'station'}`;el.innerHTML=a.kind==='hospital'?'<svg viewBox="0 0 24 24"><path d="M9 3h6v6h6v6h-6v6H9v-6H3V9h6z"/></svg>':fireBadgeSVG;el.setAttribute('aria-label',`${a.name} — operational status unknown`);el.title=a.name;const tag=document.createElement('span');tag.className='facility-name';tag.textContent=a.name.replace('Los Angeles Fire Department Fire Station','Station').replace('Los Angeles County Fire Department','County Fire').replace('Providence Saint John’s Health Center',"Saint John's");el.append(tag);const content=document.createElement('div');const heading=document.createElement('strong');heading.textContent=a.name;const detail=document.createElement('p');detail.textContent='OpenStreetMap inventory. Capacity, power and dispatch status unknown.';content.append(heading,detail);const marker=new Marker({element:el}).setLngLat(a.coordinates).setPopup(new Popup({offset:18}).setDOMContent(content)).addTo(m);inventoryMarkers.current.push({marker,kind:a.kind,id:a.id})});
   }).catch(()=>{if(!disposed)setInventoryError('Infrastructure inventory unavailable')});
   zones.forEach(z=>{const el=document.createElement('button');el.className='geo-marker zone';el.textContent=`ZONE ${z.id}`;el.setAttribute('aria-label',`Select exercise Zone ${z.id}: ${z.name}`);el.onclick=()=>setZone(z.id);zoneMarkers.current.push(new Marker({element:el}).setLngLat(z.center as [number,number]).addTo(m))});
  });
  m.on('error',e=>{if(disposed)return;const source=(e as unknown as {sourceId?:string}).sourceId;if(source==='elevation')return;setError('Some map tiles are unavailable. Check your connection or try the other basemap.');});
  m.on('idle',()=>{if(!disposed&&m.areTilesLoaded())setError('')});
  m.on('mousemove',e=>{const height=m.queryTerrainElevation(e.lngLat);setElevation(height==null?null:Math.round(height*3.28084))});
  const refreshClosures=async()=>{try{const r=await fetch('/ops-api/closures');if(!r.ok)return;const d=await r.json();if(disposed)return;closureMarkers.current.forEach(marker=>marker.remove());closureMarkers.current=[];const seen=new Set<string>();d.items.filter((c:any)=>c.status!=='Reported ended').forEach((c:any)=>{const key=c.coordinates.join(',');if(seen.has(key))return;seen.add(key);const el=document.createElement('button');el.className=`geo-marker closure-marker ${c.status==='Reported active'?'active':''}`;el.textContent='!';el.setAttribute('aria-label',`Caltrans ${c.road} ${c.status}: ${c.location}`);const content=document.createElement('div');const title=document.createElement('strong');title.textContent=`Caltrans · ${c.road} ${c.direction}`;const detail=document.createElement('p');detail.textContent=`${c.status}: ${c.type} closure, ${c.work}. ${c.location}. Scheduled ${c.start} to ${c.end}. Source updated ${c.updated}. Other road conditions remain unknown.`;content.append(title,detail);closureMarkers.current.push(new Marker({element:el}).setLngLat(c.coordinates).setPopup(new Popup({offset:16}).setDOMContent(content)).addTo(m))})}catch{/* Provider status is shown in the Sources panel. */}};
  refreshClosures();const closureTimer=setInterval(refreshClosures,60000);
  const observer=new ResizeObserver(()=>m.resize());observer.observe(container.current);
  return()=>{disposed=true;clearInterval(closureTimer);closureMarkers.current.forEach(marker=>marker.remove());closureMarkers.current=[];observer.disconnect();inventoryMarkers.current.forEach(({marker})=>marker.remove());inventoryMarkers.current=[];zoneMarkers.current.forEach(marker=>marker.remove());zoneMarkers.current=[];markers.current.forEach(marker=>marker.remove());markers.current=[];m.remove();map.current=null};
 },[attempt]);
 useEffect(()=>{if(!loaded||!map.current)return;(map.current.getSource('incident') as GeoJSONSource).setData(incidentData(state.condition?.type,hazardTime))},[loaded,state.condition?.type,hazardTime]);
 useEffect(()=>{if(!loaded||!map.current)return;const m=map.current;m.setLayoutProperty('topographic','visibility',basemap==='topographic'?'visible':'none');m.setLayoutProperty('satellite','visibility',basemap==='satellite'?'visible':'none');},[loaded,basemap]);
 useEffect(()=>{if(!loaded||!map.current)return;const m=map.current;m.setTerrain(terrain?{source:'elevation',exaggeration:1.35}:null);m.easeTo({pitch:terrain?58:0,bearing:terrain?-15:0,duration:700});},[loaded,terrain]);
 useEffect(()=>{if(!loaded||!map.current)return;['fire-fill','fire-edge','evacuation-fill','evacuation-line','closure','impact','ops-routes','ops-labels','blackout-fill','blackout-edge','blackout-label'].forEach(id=>map.current!.setLayoutProperty(id,'visibility',overlays?'visible':'none'));[...markers.current,...zoneMarkers.current].forEach(marker=>{marker.getElement().style.display=overlays?'':'none'});},[loaded,overlays]);
 useEffect(()=>{if(!loaded||!map.current)return;zoneMarkers.current.forEach((m,i)=>m.getElement().classList.toggle('active',zones[i].id===zone));},[loaded,zone,state.condition?.type]);
 useEffect(()=>{if(!loaded||!map.current)return;['power-inventory','power-halo','grid-fill','grid-edge','grid-label'].forEach(id=>map.current!.setLayoutProperty(id,'visibility',visibility.power?'visible':'none'));map.current.setLayoutProperty('road-inventory','visibility',visibility.road?'visible':'none');inventoryMarkers.current.forEach(({marker,kind})=>marker.getElement().style.display=visibility[kind as keyof typeof visibility]?'':'none');},[loaded,visibility,inventoryCount]);
 useEffect(()=>{const change=()=>setFull(document.fullscreenElement===panel.current);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setFull(false)};document.addEventListener('fullscreenchange',change);document.addEventListener('keydown',key);return()=>{document.removeEventListener('fullscreenchange',change);document.removeEventListener('keydown',key)}},[]);
 const toggleFull=async()=>{if(full){if(document.fullscreenElement)await document.exitFullscreen();setFull(false)}else{setFull(true);try{await panel.current?.requestFullscreen()}catch{/* Expanded viewport fallback. */}}};
 return <section ref={panel} className={`map-panel ${full?'expanded-map':''}`} aria-label="Pacific Palisades topographic map">
  <div className="map-toolbar"><div className="basemap-tabs" aria-label="Basemap"><button className={basemap==='topographic'?'selected':''} aria-pressed={basemap==='topographic'} onClick={()=>setBasemap('topographic')}>Topographic</button><button className={basemap==='satellite'?'selected':''} aria-pressed={basemap==='satellite'} onClick={()=>setBasemap('satellite')}>Satellite</button></div><div className="map-actions"><button onClick={toggleFull} aria-label={full?"Exit full-screen map":"Full-screen map"}>{full?<Minimize size={18}/>:<Maximize size={18}/>}<span>{full?"Exit full screen":"Full screen"}</span></button><button aria-pressed={terrain} className={terrain?'selected':''} onClick={()=>setTerrain(!terrain)}><Mountain size={17}/>3D terrain</button><button aria-label="Fit incident area" onClick={()=>{setTerrain(false);map.current?.fitBounds(INCIDENT_BOUNDS,{padding:35,pitch:0,bearing:0,duration:600})}}><LocateFixed size={18}/></button><button aria-label="Map layers" aria-expanded={layersOpen} onClick={()=>setLayersOpen(!layersOpen)}><Layers size={18}/></button></div></div>
  <div className="real-map" ref={container}/><div className="coverage-note" title={inventoryCount}>{inventoryError||"EXERCISE · Real streets / simulated movement"}</div><div className="facility-controls"><button className={facilityView==='hospital'?'selected':''} onClick={()=>{setVisibility(v=>({...v,hospital:true}));setFacilityView(facilityView==='hospital'?null:'hospital')}}><Hospital size={17}/>Hospitals <b>{facilities.filter(f=>f.kind==='hospital').length}</b></button><button className={facilityView==='fire_station'?'selected':''} onClick={()=>{setVisibility(v=>({...v,fire_station:true}));setFacilityView(facilityView==='fire_station'?null:'fire_station')}}><FireBadge size={20}/>Fire stations <b>{facilities.filter(f=>f.kind==='fire_station').length}</b></button><button className={powerFocus?"selected":""} onClick={()=>{setPowerFocus(!powerFocus);setVisibility(v=>({...v,power:true}));setFacilityView(null)}}><Zap size={17}/>Power network</button></div>{powerFocus&&<div className="power-directory"><strong><Zap size={18}/>Electrical network</strong><p><i className="power-swatch"/>88 mapped line segments · purple</p><p><i className="powered-swatch"/>Green areas: simulated power on</p><p><i className="blackout-swatch"/>Dark areas: simulated blackout</p><small>Mapped coverage is incomplete. Actual line energization is unknown; area power states are exercise data.</small><button onClick={()=>map.current?.fitBounds(INCIDENT_BOUNDS,{padding:60,pitch:0,bearing:0,duration:700})}>Show regional network</button></div>}{facilityView&&<div className="facility-directory"><div><strong>{facilityView==='hospital'?'Hospitals & medical sites':'Fire stations & service sites'}</strong><button aria-label="Close facility directory" onClick={()=>setFacilityView(null)}><X size={15}/></button></div><small>Mapped coverage · select a site to locate it. Service sites include helispots. Operating status unknown.</small><button className="show-all-facilities" onClick={()=>map.current?.fitBounds(INCIDENT_BOUNDS,{padding:60,pitch:0,bearing:0,duration:700})}>Show all on map</button>{facilities.filter(f=>f.kind===facilityView).map(f=><button className="facility-list-item" key={f.id} onClick={()=>{inventoryMarkers.current.forEach(({marker})=>{if(marker.getPopup()?.isOpen())marker.togglePopup()});map.current?.flyTo({center:f.coordinates,zoom:14.2,duration:800});inventoryMarkers.current.find(m=>m.id===f.id)?.marker.togglePopup()}}>{facilityView==='hospital'?<Hospital size={18}/>:<FireBadge size={20}/>}<span>{f.name}</span><span>↗</span></button>)}</div>}{loaded&&map.current&&<MapSimulation map={map.current} condition={state.condition?.type} visible={overlays} zone={zone} onZone={setZone} onNotified={onNotified} onElapsed={setHazardTime}/>}
  {!loaded&&!error&&<div className="map-loading"><Mountain size={24}/><strong>Loading topographic map</strong><span>Pacific Palisades · USGS</span></div>}
  {error&&<div className="map-error" role="status"><span>{error}</span><button onClick={()=>setAttempt(n=>n+1)}>Retry map</button></div>}
  {layersOpen&&<div className="map-layer-menu"><div><strong>Map layers</strong><button aria-label="Close layers" onClick={()=>setLayersOpen(false)}><X size={16}/></button></div><label><input type="checkbox" checked={overlays} onChange={e=>setOverlays(e.target.checked)}/>Simulated incident overlays</label>{(['hospital','fire_station','power','road'] as const).map(k=><label key={k}><input type="checkbox" checked={visibility[k]} onChange={e=>setVisibility(v=>({...v,[k]:e.target.checked}))}/>{{hospital:'Hospitals',fire_station:'Fire stations',power:'Power lines · state unknown',road:'Road network · state unknown'}[k]}</label>)}<p>Roads, contours, and place names are included in the USGS basemap.</p></div>}
  {state.condition&&<div className="map-condition"><RadioTower size={18}/><div><strong>{state.condition.type.replaceAll('_',' ')}</strong><span>{state.condition.target}</span></div></div>}
  <div className="map-legend"><span><Hospital size={14}/>Hospital</span><span><FireBadge size={17}/>Fire station</span><span><i className="legend-fire"/>Fire perimeter</span><span><i className="legend-evac"/>Evacuation zone</span><span><i className="legend-power"/>Power lines</span><span><i style={{background:"#42ae83"}}/>Power on · demo</span><span><i style={{background:"#34495f"}}/>Blackout · demo</span><span><i className="legend-closure"/>Caltrans record</span><span><i className="legend-egress"/>Demo egress</span><span><i className="legend-responder"/>Demo engines</span><span className="map-data-note">Real geography · Simulated incident</span>{terrain&&elevation!==null&&<span>{elevation.toLocaleString()} ft</span>}</div>
 </section>
});
