import { useEffect, useRef, useState } from 'react';
import { Bell, BellOff, RefreshCw } from 'lucide-react';
type Feed={fetchedAt?:string;items?:any[];error?:string};
export function LiveFeeds(){
 const [weather,setWeather]=useState<Feed>({});const [roads,setRoads]=useState<Feed>({});const [connections,setConnections]=useState<any>({});const [busy,setBusy]=useState(false);const [alarm,setAlarm]=useState(false);const audio=useRef<AudioContext|null>(null);const [audioError,setAudioError]=useState('');
 const refresh=async()=>{setBusy(true);await Promise.all([['weather',setWeather],['closures',setRoads],['connections',setConnections]].map(async([name,setter])=>{try{const r=await fetch(`/ops-api/${name}`);const d=await r.json();(setter as any)(d)}catch{(setter as any)({error:'Local provider bridge unavailable'})}}));setBusy(false)};
 useEffect(()=>{refresh();const t=setInterval(refresh,60000);return()=>{clearInterval(t);audio.current?.close()}},[]);
 const sound=async()=>{if(audio.current){await audio.current.close();audio.current=null;setAlarm(false);return}try{const ctx=new AudioContext();audio.current=ctx;await ctx.resume();const gain=ctx.createGain();gain.gain.value=.07;gain.connect(ctx.destination);const oscillator=ctx.createOscillator();oscillator.type='sine';oscillator.connect(gain);const t=ctx.currentTime;for(let i=0;i<6;i++){oscillator.frequency.setValueAtTime(520,t+i);oscillator.frequency.linearRampToValueAtTime(780,t+i+.5);oscillator.frequency.linearRampToValueAtTime(520,t+i+1)}oscillator.start();oscillator.stop(t+6);setAlarm(true);oscillator.onended=()=>{if(audio.current===ctx){ctx.close();audio.current=null;setAlarm(false)}}}catch{setAudioError('Browser audio unavailable.')}};
 return <><div className="tower-label">Live public feeds <span>Separate from exercise</span></div><button className="wide" disabled={busy} onClick={refresh}><RefreshCw size={16}/>{busy?'Fetching providers…':'Refresh public feeds'}</button><div className="alarm-box"><button className={alarm?'alarm-active':'wide'} onClick={sound}>{alarm?<BellOff size={17}/>:<Bell size={17}/>} {alarm?'Silence / acknowledge':'Test local alarm · 6 seconds'}</button><small>{audioError||'Browser speaker only. No external sirens are connected.'}</small></div>
 <div className="source-card"><strong>National Weather Service</strong><b>{weather.error?'Feed unavailable':weather.fetchedAt?'Connected · polling every minute':'Connecting…'}</b><small>{weather.error||`Fetched ${weather.fetchedAt?new Date(weather.fetchedAt).toLocaleTimeString():'—'}. Coverage: incident center point.`}</small>{weather.items?.length===0&&<p>No active NWS alerts returned for this point. This does not indicate all hazards are absent.</p>}{weather.items?.map(a=><div className="report-entry" key={a.id}><strong>{a.event}</strong><p>{a.headline}</p><small>Issued {a.sent} · expires {a.expires}</small><p>{a.instruction}</p></div>)}</div>
 <div className="source-card"><strong>Caltrans · District 7 lane closures</strong><b>{roads.error?'Feed unavailable':roads.fetchedAt?'Connected · polling every minute':'Connecting…'}</b><small>{roads.error||`Fetched ${roads.fetchedAt?new Date(roads.fetchedAt).toLocaleTimeString():'—'}. Provider times are local.`}</small><p>State-highway lane-closure records within the response area. No record does not mean a road is open; local closures and traffic speeds are not included.</p>{roads.items?.length===0&&<p>No records returned in the response area.</p>}{roads.items?.slice(0,15).map(r=><div className="report-entry" key={r.id}><strong>{r.road} · {r.direction} · {r.location}</strong><p>{r.status} · {r.type} closure · {r.work}</p><small>{r.start} → {r.end}<br/>Source updated: {r.updated}</small></div>)}{(roads.items?.length||0)>15&&<small>Showing 15 of {roads.items?.length} records.</small>}</div>
 <div className="source-card"><strong>Twilio SMS</strong><b>{connections.twilio||connections.error||'Checking configuration…'}</b><p>Add TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN and TWILIO_MESSAGING_SERVICE_SID to frontend/.env.local, then restart Vite. Secrets stay on the server.</p><small>Credential detection only. Production sending, approved recipient lists and verified delivery callbacks still need integration.</small></div>
 </>;
}
