import { useEffect, useRef, useState } from 'react';
import { Marker, type Map as MapLibre, type GeoJSONSource } from 'maplibre-gl';
import { Pause, Play, RotateCcw, Bell, ChevronDown } from 'lucide-react';
import { vehiclePhase } from './playback';
import { blackoutGeometry, poweredGeometry, outageAreas } from './hazardEvolution';
import { routeDecision, type ZoneId } from './operations';
export type MotionRoute={id:string;label:string;kind:'civilian'|'engine';coordinates:[number,number][];returnCoordinates?:[number,number][];streets:string[];length:number};
export function distance(a:number[],b:number[]){return Math.hypot((a[0]-b[0])*.829,a[1]-b[1])*111320}
const routeDistances=new WeakMap<MotionRoute,{lengths:number[];total:number}>();
export function positionAlong(route:MotionRoute,fraction:number){let cached=routeDistances.get(route);if(!cached){const lengths=route.coordinates.slice(1).map((p,i)=>distance(route.coordinates[i],p));cached={lengths,total:lengths.reduce((a,b)=>a+b,0)};routeDistances.set(route,cached)}const {lengths,total}=cached;const target=Math.max(0,Math.min(1,fraction))*total;let sum=0;for(let i=0;i<lengths.length;i++){if(sum+lengths[i]>=target||i===lengths.length-1){const a=route.coordinates[i],b=route.coordinates[i+1],t=lengths[i]?(target-sum)/lengths[i]:0;return {point:[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t] as [number,number],bearing:Math.atan2((b[0]-a[0])*.829,b[1]-a[1])*180/Math.PI}}sum+=lengths[i]}return {point:route.coordinates[0],bearing:0}}
export const vehicleSVG=(engine:boolean)=>engine?'<svg viewBox="0 0 20 36" aria-hidden="true"><rect x="2" y="1" width="16" height="34" rx="4" fill="#fb7549" stroke="white" stroke-width="2"/><path d="M5 9h10M6 16h8v14H6zM8 17v12m4-12v12" fill="none" stroke="#612919" stroke-width="2"/><path d="M4 5h5" stroke="#66ddff" stroke-width="3"/><path d="M11 5h5" stroke="#fff" stroke-width="3"/></svg>':'<svg viewBox="0 0 16 28" aria-hidden="true"><rect x="2" y="1" width="12" height="26" rx="4" fill="#15aab0" stroke="white" stroke-width="1.5"/><path d="M4 7h8v5H4zm0 11h8v4H4z" fill="#123c4a"/><path d="M4 3h2m4 0h2" stroke="#e5ffff" stroke-width="2"/></svg>';
export function MapSimulation({map,condition,visible,zone,onZone,onNotified,onElapsed}:{map:MapLibre;condition?:string;visible:boolean;zone:ZoneId;onZone:(z:ZoneId)=>void;onNotified:(n:number)=>void;onElapsed:(n:number)=>void}){
 const [routes,setRoutes]=useState<MotionRoute[]>([]);const [error,setError]=useState('');const [playing,setPlaying]=useState(false);const [speed,setSpeed]=useState(1);const [elapsed,setElapsed]=useState(0);const [expanded,setExpanded]=useState(false);const clock=useRef(0);const playingRef=useRef(false);const speedRef=useRef(1);const conditionRef=useRef(condition);
 playingRef.current=playing;speedRef.current=speed;conditionRef.current=condition;
 useEffect(()=>{fetch('/data/motion-routes.json').then(r=>{if(!r.ok)throw Error('Route geometry unavailable');return r.json()}).then(setRoutes).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!routes.length)return;const data={type:'FeatureCollection' as const,features:routes.map(r=>({type:'Feature' as const,properties:{kind:r.kind==='engine'?'responder':'egress',name:r.kind==='engine'?r.label:`Zone ${r.id} residents`,status:r.kind==='civilian'&&!routeDecision(r.id[0] as ZoneId,condition).available?'held':'candidate'},geometry:{type:'LineString' as const,coordinates:r.coordinates}}))};(map.getSource('operations') as GeoJSONSource).setData(data)},[map,routes,condition]);
 useEffect(()=>{if(!routes.length)return;const vehicles=routes.flatMap((r,routeIndex)=>Array.from({length:r.kind==='engine'?1:24},(_,i)=>{const el=document.createElement('div');el.className=`motion-vehicle ${r.kind}`;el.innerHTML=vehicleSVG(r.kind==='engine');el.title=`${r.label} · simulated movement`;const marker=new Marker({element:el,rotationAlignment:'map',pitchAlignment:'map'}).setLngLat(r.coordinates[0]).addTo(map);return {marker,route:r,returnRoute:{...r,coordinates:r.returnCoordinates||r.coordinates},index:i,routeIndex,progress:0,returning:false}}));let frame=0,last=0,paint=0,hud=0;
 const tick=(now:number)=>{const dt=last?Math.min((now-last)/1000,.1):0;last=now;if(playingRef.current)clock.current+=dt*speedRef.current;if(now-paint>33){paint=now;vehicles.forEach(v=>{const civilian=v.route.kind==='civilian';const held=civilian&&!routeDecision(v.route.id[0] as ZoneId,conditionRef.current).available;const departure=civilian?2+(v.routeIndex%5)*2+v.index*2.5:2+(v.routeIndex%8)*4;const phase=vehiclePhase(clock.current,departure,civilian?110+(v.routeIndex%4)*8:95,!civilian);const show=visible&&phase.visible;v.marker.getElement().style.display=show?'':'none';if(show){if(!held){v.progress=phase.fraction;v.returning=phase.returning}const p=positionAlong(v.returning?v.returnRoute:v.route,v.progress);v.marker.setLngLat(p.point).setRotation(p.bearing);v.marker.getElement().classList.toggle('held',held)}})}if(now-hud>300){hud=now;setElapsed(clock.current);}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);vehicles.forEach(v=>v.marker.remove())}},[map,routes,visible]);
 const progress=['A','B','C'].map((id,i)=>({id:id as ZoneId,count:Math.round(Math.min(1,Math.max(0,(elapsed-i*8)/24))*[420,680,310][i]),total:[420,680,310][i]}));
 const notified=progress.reduce((s,z)=>s+z.count,0);
 useEffect(()=>onNotified(notified),[notified,onNotified]);
 const seconds=Math.floor(elapsed);
 useEffect(()=>{onElapsed(seconds);(map.getSource('blackouts') as GeoJSONSource).setData(blackoutGeometry(seconds));(map.getSource('grid') as GeoJSONSource).setData(poweredGeometry(seconds))},[seconds,map,onElapsed]);
 const outages=outageAreas.filter(a=>elapsed>=a.start);

 return <div className="simulation-dock" aria-label="Simulation controls"><details className="scenario-status"><summary>Conditions <ChevronDown size={14}/></summary><span>SIMULATED CONDITIONS</span><div><b>{routes.filter(r=>r.kind==='civilian').length} routes / {routes.filter(r=>r.kind==='civilian').length*24} cars</b><b>{routes.filter(r=>r.kind==='engine').length} fire units</b></div><p><i className="spread-dot"/>Fire perimeter +{Math.round(Math.min(elapsed/180,1)*12)}%</p><p><i className="outage-dot"/>{outages.length} blackout areas · {outages.reduce((n,a)=>n+a.homes,0)} homes</p><small>{outages.length?outages.map(a=>a.name.split(' ·')[0]).join(' / '):"Power disruption develops during playback"}</small></details><div className="motion-console"><div className="motion-top"><div><span className="motion-dot"/> MOVEMENT SIMULATION</div><span>{Math.floor(elapsed/60).toString().padStart(2,'0')}:{Math.floor(elapsed%60).toString().padStart(2,'0')}</span></div><div className="motion-controls"><button disabled={!routes.length} onClick={()=>{setPlaying(!playing)}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause':'Play simulation'}</button><button aria-label="Restart movement simulation" onClick={()=>{clock.current=0;setElapsed(0);setPlaying(false)}}><RotateCcw size={16}/></button><select aria-label="Simulation playback speed" value={speed} onChange={e=>setSpeed(+e.target.value)}><option value={1}>1×</option><option value={2}>2×</option><option value={4}>4×</option></select></div><div className="motion-key"><span><i/>Residents</span><span><i/>Fire engines</span><span>Continuous dispatch</span></div><button className="notification-toggle" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}><Bell size={15}/>{progress.reduce((s,z)=>s+z.count,0).toLocaleString()} / 1,410 demo households notified<ChevronDown size={14}/></button>{expanded&&<div className="motion-zones">{progress.map(z=><button className={zone===z.id?'selected':''} key={z.id} onClick={()=>onZone(z.id)}><strong>Zone {z.id} <span>{z.count}/{z.total}</span></strong><div className="notify-track"><i style={{width:`${z.count/z.total*100}%`}}/></div><small>{routeDecision(z.id,condition).available?(z.count===z.total?'Notified · departures in progress':z.count?'Notification in progress':'Awaiting notification'):'Traffic held · reassessment'}<br/>{routes.find(r=>r.id===z.id)?.streets.join(' → ')}</small></button>)}<p>Fictional households. No texts sent. Animation represents accelerated exercise traffic, not live vehicle locations.</p></div>}{error&&<p role="alert">{error}</p>}</div></div>
}
